# Site settings
title: Ücretsiz etkinlik, gezi, düğün, kafe sitesi oluştur - davetlimiz.com
email: proxima@ekofi.science
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://davetlimiz.com" # the base hostname & protocol for your site
twitter_username: davetlimiz
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
